channel_sources:
  - conda-forge,tiledb
channel_targets:
  - tiledb for-cloud
channel_priority:
  - strict
numpy:
  - 1.22
  - 1.22
python:
  - 3.8.* *_cpython
  - 3.9.* *_cpython
python_impl:
  - cpython
  - cpython
r_base:
  - 4.3
c_compiler:
  - gcc
c_compiler_version:
  - '12'
cxx_compiler:
  - gxx
cxx_compiler_version:
  - '12'
