channel_sources:
  - conda-forge,tiledb
channel_targets:
  - tiledb for-cloud
channel_priority:
  - strict
numpy:
  - 1.22
  - 1.22
python:
  - 3.8.* *_cpython
  - 3.9.* *_cpython
python_impl:
  - cpython
  - cpython
r_base:
  - 4.3
libarrow:
  - 14
arrow_cpp:
  - 14
libarrow_all:
  - 14
pyarrow:
  - 14
r_arrow:
  - 14
pin_run_as_build:
  pyarrow:
    min_pin: x
    max_pin: x
