{% set name = "tiledb-stack" %}
{% set version = "2.18.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/TileDB-Inc/TileDB/releases/download/2.18.3/tiledb-linux-x86_64-noavx2-2.18.3-8f8b766.tar.gz
    folder: TileDB/
    sha256: 09d5c654c8f0e24c7d6abc50cf631edcbbe22598825be5ee2d6bfa0425e9ea4f
  - git_url: https://github.com/TileDB-Inc/TileDB-Py.git
    git_rev: 0.24.0
    folder: TileDB-Py/
  - git_url: https://github.com/TileDB-Inc/TileDB-R.git
    git_rev: 0.22.0
    folder: TileDB-R/
  - git_url: https://github.com/TileDB-Inc/TileDB-VCF.git
    git_rev: 0.27.1
    folder: TileDB-VCF/

outputs:
  - name: tiledb
    version: {{ version }}
    script: build-tiledb.sh
    build:
      number: 0
      run_exports:
        # https://abi-laboratory.pro/?view=timeline&l=tiledb
        - {{ pin_subpackage('tiledb', min_pin='x.x', max_pin='x.x') }}
    test:
      requires:
        - {{ compiler('cxx') }}
        - cmake
        - make
      commands:
        - test -e $PREFIX/include/tiledb/tiledb.h
        - test -e $PREFIX/include/tiledb/tiledb
        - test -e $PREFIX/lib/libtiledb$SHLIB_EXT
        - bash test-tiledb-linking.sh
    about:
      home: http://tiledb.io
      license: MIT
      license_family: MIT
      license_file: LICENSE
      summary: TileDB sparse and dense multi-dimensional array data management
      description: |
        TileDB is an efficient multi-dimensional array management system which introduces
        a novel on-disk format that can effectively store dense and sparse array data with
        support for fast updates and reads. It features excellent compression, and an efficient
        parallel I/O system with high scalability.
      doc_url: http://docs.tiledb.io
      dev_url: https://github.com/TileDB-Inc/TileDB
  - name: tiledb-py
    version: 0.25.0
    script: build-tiledb-py.sh
    build:
      number: 0
    requirements:
      build:
        - {{ compiler('cxx') }}
      host:
        - pip
        - wheel
        - setuptools
        - setuptools_scm
        - python
        - cython <3.0
        - numpy
        - pybind11 <2.11
        - {{ pin_subpackage('tiledb', exact=True) }}
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - packaging
        - {{ pin_subpackage('tiledb', exact=True) }}
    test:
      requires:
        - hypothesis
        - pyarrow
        - pytest
        - pandas
        - psutil
      imports:
        - tiledb
      source_files:
        - TileDB-Py/tiledb/tests/
      commands:
        - python -c "import tiledb; tiledb.libtiledb.version()"
        - python -c "import tiledb; assert tiledb.VFS().supports('s3')"
        - cd TileDB-Py && pytest -v --ignore-glob='*_examples.py' --ignore-glob='*_dask.py'
    about:
      home: http://tiledb.io
      license: MIT
      license_family: MIT
      license_file: LICENSE
      summary: Python interface to the TileDB sparse and dense multi-dimensional array storage manager
      description: |
        TileDB-Py is the python interface to the TileDB array storage manager.
        TileDB  is an efficient multi-dimensional array management system which introduces
        a novel on-disk format that can store dense and sparse array data with
        support for fast reads and updates and reads. It features excellent compression, and an efficient
        parallel I/O system with high scalability.
      doc_url: https://api-reference.tiledb.io/python-api.html
      dev_url: https://github.com/TileDB-Inc/TileDB-Py
  - name: r-tiledb
    version: 0.23.0
    script: build-tiledb-r.sh
    build:
      number: 0
      rpaths:
        - lib/R/lib/
        - lib/
    requirements:
      build:
        - {{ compiler('cxx') }}
        - pkg-config
        - make
      host:
        - r-base
        - {{ pin_subpackage('tiledb', exact=True) }}
        - r-rcpp >=1.0.8
        - r-rcppspdlog
        - r-nanotime
        - r-spdl
        - r-rcppint64
      run:
        - r-base
        - r-nanotime
        - r-spdl
        - {{ pin_subpackage('tiledb', exact=True) }}
    test:
      requires:
        - r-tinytest
        - r-nycflights13
        - r-palmerpenguins
        - r-data.table
      commands:
        - Rscript -e 'tinytest::test_package("tiledb")'
    about:
      home: https://www.tiledb.com
      license: MIT
      license_file:
        - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
        - LICENSE
      summary: R interface to the TileDB array storage manager
      description: |
        TileDB is a highly-parallelized, cloud native array storage engine.
      doc_url: https://docs.tiledb.com/developer/
      dev_url: https://github.com/TileDB-Inc/TileDB-R
  - name: libtiledbvcf
    version: 0.27.1
    script: build-tiledb-vcf.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - git
        - cmake
        - make
      host:
        - htslib >=1.15
        - {{ pin_subpackage('tiledb', exact=True) }}
      run:
        - htslib >=1.15
        - {{ pin_subpackage('tiledb', exact=True) }}
    test:
      files:
        - test-cli.sh
      commands:
        - tiledbvcf version
        # verify libhts is linked
        - ldd ${PREFIX}/lib/libtiledbvcf.so | grep libhts
        # verify libdeflate is linked to libhts
        - ldd ${PREFIX}/lib/libhts.so.* | grep libdeflate
        - tiledbvcf create --uri /tmp/test-tiledbvcf-conda
        - bash test-tiledb-vcf-cli.sh
  - name: tiledbvcf-py
    version: 0.27.1
    script: build-tiledb-vcf-py.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
      host:
        - numpy
        - {{ pin_subpackage('libtiledbvcf', exact=True) }}
        - python
        - pyarrow  {{ pyarrow }}
        - pybind11 >=2.5
        - wheel >=0.30
        - setuptools >=18.0
        - setuptools_scm 6.0.1
        - setuptools_scm_git_archive
      run:
        - {{ pin_compatible('numpy', lower_bound='1.16', upper_bound='1.24') }}
        - {{ pin_subpackage('libtiledbvcf', exact=True) }}
        - python
        - {{ pin_compatible('pyarrow', max_pin='x') }}
        - pandas
    imports:
      - tiledbvcf
    test:
      files:
        - test-api.py
      commands:
        - python -c "import tiledbvcf; tiledbvcf.version"
        - python test-tiledb-vcf-api.py
  - name: tiledb-stack
    version: 2.18.3
    build:
      number: 0
    requirements:
      run:
        - {{ pin_subpackage('tiledb', exact=True) }}
        - {{ pin_subpackage('tiledb-py', exact=True) }}
        - {{ pin_subpackage('r-tiledb', exact=True) }}
        - {{ pin_subpackage('libtiledbvcf', exact=True) }}
        - {{ pin_subpackage('tiledbvcf-py', exact=True) }}
    about:
      home: https://www.tiledb.com
      summary: TileDB Cloud stack
      description: |
        The conda binaries deployed to TileDB Cloud

about:
  home: http://tiledb.io
  license: MIT
  license_family: MIT
  summary: TileDB stack to deploy to TileDB Cloud
  description: |
    Special set of linux binaries for easy deployment
  doc_url: http://docs.tiledb.io
  dev_url: https://github.com/TileDB-Inc/TileDB

extra:
  recipe-maintainers:
    - ihnorton
    - jdblischak
    - shelnutt2
