name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - name: Build
      env:
        AWS_ACCESS_KEY_ID: {{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: {{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        python3 build-locally.py
